### PR TITLE
Created initial Password_generator.py

### PR DESCRIPTION
**Pull request by Saurabh-2809**
Hi Sourav, I have created a password generator program that will provide two passwords,

1 easy password: Here letters, numbers, and symbols will not be random in order.
2 hard password: Everything will be in random order.

### CODE REVIEW

**Comment by glacias07** [comment]
You can maybe modularize your code by making small functions that just do 1 single function and call them inside a main function. It's a good practice and makes debugging and understanding the code simpler.

**Comment by Saurabh-2809** [comment]
Hi @glacias07, thanks for the suggestion, let me modularize the code.

**Comment by glacias07** [comment]
@Saurabh-2809 looks great

**Comment by Saurabh-2809** [comment]
Hi @souravjain540, could you please review my PR #58 and merge it if there is no issue?

**Review by souravjain540 — APPROVED** [review]

**Pull request merged**
