### PR TITLE
Add 6 new programs.

### PR DESCRIPTION
**Pull request by SaadAnsari17**
Add 8 new programs
1) insertion_sort.py
2) linear_search.py
3)  linked_list.py
4) postfixeval.py
5)  selection_sort.py
6)  stack.py
7) binary_search_tree.py
8) queue.py

### CODE REVIEW

**Comment by SaadAnsari17** [comment]
What's spam in this ?
image
You recommended multiple progs in one pr.

**Comment by souravjain540** [comment]
> @souravjain540 What's spam in this?
> 
> image
> 
> You recommended multiple progs in one pr.

Deletion of comments. Please make a new PR without them.

**Comment by SaadAnsari17** [comment]
Oh!! I'm so sorry for that, I by mistakenly deleted those comments while I was removing comments from my programs that I wrote for my understanding.

**Comment by SaadAnsari17** [comment]
@souravjain540  I request you to remove the spam label because I didn't intend to do that.

**Comment by SaadAnsari17** [comment]
Made pr #109

**Pull request closed without merging**
