### PR TITLE
Added quadratic_equation.py file

### PR DESCRIPTION
**Pull request by Berneyw**
I added a python script that solves easy quadratic equations

### CODE REVIEW

**Comment by Berneyw** [comment]
sup i need review

**Review by jheavejimenez — CHANGES_REQUESTED** [review]
Hi, @BernEsports 

here's some suggestions to improve it

**User Input Validation:** You should add some validation to ensure that the user enters valid numerical values for a, b, and c. If a non-numeric value is entered, your current code will raise a ValueError when trying to convert the input to integers. You can use a try-except block to handle this more gracefully.

**Review by Berneyw — COMMENTED** [review]
Exception added

**Review by jheavejimenez — APPROVED** [review]
LGTM

**Review by abhinab-choudhury — COMMENTED** [review]
All good

**Review by abhinab-choudhury — APPROVED** [review]

**Pull request closed without merging**
